### ISSUE TITLE
Broken links in Tutorial ipynb

### ISSUE THREAD

**Issue by elijahc** [AllenInstitute/bmtk#11]
The [tutorial ipynb](https://github.com/AllenInstitute/bmtk/blob/develop/docs/tutorial/00_introduction.ipynb) has some tutorials for PointNet and PopNet (Ch. 4 and Ch. 5) I was interested in reading about but the links are broken

**Broken Links:**
>### Part 1: Complete workflow tutorials
>...
>[Chapter 5: Point-neuron simulation (with PointNet)](05_pointnet_tut.ipynb)
>[Chapter 6: Population-level simulation (with PopNet)](06_popnet_tut.ipynb)

**Comment by kaeldai** [comment]
Tutorials for Point and Population level modeling have been added.
