### ISSUE TITLE
example "1cell_all_active" unrunnable 

### ISSUE THREAD

**Issue by caparvulus** [AllenInstitute/bmtk#12]
there is no file called "318331342_fit.json", and also even if I changed to some existing file, it would still give me error TypeError: init() got multiple values for keyword argument 'network'
at line 24: sim = Simulation(conf, network=net) # initialize a simulation

I asked this question as a followup from https://github.com/AllenInstitute/AllenSDK/issues/107

**Comment by kaeldai** [comment]
Hi,
It looked like the example for an all-axon axon simulation was outdated. I fixed the script and I also add the necessary parameters and morphology files. Thanks for letting us know.
