### ISSUE TITLE
astype() got an unexpected keyword argument 'copy'

### ISSUE THREAD

**Issue by ConBke** [AllenInstitute/bmtk#144]
When I run the codes in the tutorial, I keep coming into the error: astype() got an unexpected keyword argument 'copy'. I have no idea how to solve it. I read some reports that the version of h5py and pandas should be downgraded to 2.8 and 0.23 respectively, but I tried and encountered another problem : "Error: Fail to build wheel for pandas"

**Comment by tjbanks** [comment]
A temporary fix (until BMTK is updated to use the later versions of pandas and h5py) is to create a new environment and re-install. In an Anaconda prompt this will get you going again:
```
conda create -n newenv python=3.6
conda activate newenv
pip install h5py==2.7.0 pandas==0.23.0
git clone https://github.com/alleninstitute/bmtk
cd bmtk
python setup.py install
```

**Comment by ConBke** [comment]
> A temporary fix (until BMTK is updated to use the later versions of pandas and h5py) is to create a new environment and re-install. In an Anaconda prompt this will get you going again:
> 
> ```
> conda create -n newenv python=3.6
> conda activate newenv
> pip install h5py==2.7.0 pandas==0.23.0
> git clone https://github.com/alleninstitute/bmtk
> cd bmtk
> python setup.py install
> ```

Thank you very much! The problem is solved, thank you again!
