### ISSUE TITLE
The Python 3.7 builds are failing

### ISSUE THREAD

**Issue by Helveg** [AllenInstitute/bmtk#154]
Hi, I also posted this somewhere obscurer but thought it was worth bringing to your attention in a seperate issue: All the Travis Python 3.7 pipelines are failing. The errors that are listed seem quite familiar and iirc are caused by a Cython version that is too old. You should try upgrading to the latest Cython before the step that errors out 👍

**Comment by kaeldai** [comment]
Thank you for reporting this, the .travis.yml has been fixed and builds should now work again.
