### ISSUE TITLE
Problem with ECP calculation when using Neuron 7.8.2

### ISSUE THREAD

**Issue by atleer** [AllenInstitute/bmtk#164]
Hi,

There seems to be an issue with the calculation of the ECP when using the latest version of Neuron (7.8.2). Running, for example, the bio_450cells_exact example provided with BMTK I get the following warning:

/Users/atleeskelandrimehaug/sources/bmtk_test_py3_6/bmtk/bmtk/simulator/bionet/modules/ecp.py:283: RuntimeWarning: invalid value encountered in true_divide
  rll = abs(rlldl / dlmag)  # component of r parallel to the segment axis it must be always positive

And in the ecp.h5 output file all values are NaN.

There are no problems with earlier versions of Neuron (I haven't testet all, of course, but 7.8.0 f. ex. works fine), so I'm merely posting this to bring it to your attention.

**Comment by kaeldai** [comment]
It looks like there was an issue with newer versions of neuron morphology api needing to make some of the parameters more explicit. It should be fixed and I am seeing the same results for neuron 7.8.2 as well as older versions (also compared 7.5 and 7.6).
