### ISSUE TITLE
"netcon_report" fails when using MPI

### ISSUE THREAD

**Issue by tjbanks** [AllenInstitute/bmtk#175]
Adding the following to a simulation config file: 

```
  "reports": {
    "syn_report": {
      "cells": [0,50,100,200,300,400,500,600,700,750],
      "variable_name": "igaba",
      "module": "netcon_report",
      "sections": "all",
      "syn_type": "interD2pyrD_SOM2P_STFD"
    }
  },

```

results in the following while running in parallel:
```
>>> Traceback (most recent call last):
  File "run_network.py", line 55, in <module>
    run(sys.argv[-1])
  File "run_network.py", line 49, in run
    sim.run()
  File "/home/tbg28/nrn/utils/conda/envs/py36/lib/python3.6/site-packages/bmtk-0.0.8-py3.6.egg/bmtk/simulator/bionet/biosimulator.py", line 344, in run
    mod.finalize(self)
  File "/home/tbg28/nrn/utils/conda/envs/py36/lib/python3.6/site-packages/bmtk-0.0.8-py3.6.egg/bmtk/simulator/bionet/modules/record_netcons.py", line 153, in finalize
    self._var_recorder.close()
  File "/home/tbg28/nrn/utils/conda/envs/py36/lib/python3.6/site-packages/bmtk-0.0.8-py3.6.egg/bmtk/utils/reports/compartment/compartment_writer.py", line 379, in close
    self._h5_handle.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

This should also be true for https://github.com/AllenInstitute/bmtk/blob/develop/docs/examples/bio_stp_models/config.json
added in [PR#67](https://github.com/AllenInstitute/bmtk/pull/67)

Example MPI command:
```
mpirun -n 10 nrniv -mpi -python run_network.py simulation_config.json
```

**Comment by kaeldai** [comment]
Hi @tjbanks, sorry for not getting back to you sooner.

It looks like the issue is how bmtk/MPI is splitting up different cells across the ranks (ie cores). Some of the ranks don't have any local cells to record from so CompartmentWriter._h5_handle is never initialize. I'm fixing this right now and should include it with a new release by the end of the day. It just need to add some checks in compartment_writer's close() and merge() methods.

**Comment by tjbanks** [comment]
You're amazing @kaeldai! I wanted to follow this up with a pull request but admittedly got lost.

Have been using this module in single core mode over the past week but runs take 6 hours rather than the normal 5 minutes in parallel --- which is fine but this will make a huge difference!

Thank you again,
Tyler

**Comment by tjbanks** [comment]
Just tested your merge and it works like a dream - thanks again @kaeldai!
