### ISSUE TITLE
pip installable

### ISSUE THREAD

**Issue by wvangeit** [AllenInstitute/bmtk#18]
Just a suggestion, maybe you can also tell users they can install bmtk using:
pip install  git+https://github.com/AllenInstitute/bmtk.git

Maybe you could also upload it to pypi ? (I saw the bmtk name is still available, could be useful to register it at least so that no other python project can use it)

**Comment by kaeldai** [comment]
Took a while but we finally go around to putting bmtk up on pypi. Thanks for the suggestion.
