### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by gkocker** [AllenInstitute/bmtk#2]
Some more documentation in the readme file would be great. What levels of resolution are described? What is its logic for building and running models and storing results, and what need does the package fill? Is there a jupyter notebook tutorial or something to help people get started?

**Comment by kaeldai** [comment]
We now have a collection of tutorials across the different levels of resolutions that can be found here:
https://github.com/AllenInstitute/bmtk/blob/develop/docs/tutorial/00_introduction.ipynb
