### ISSUE TITLE
Recording variables with different DT

### ISSUE THREAD

**Issue by GregGlickert** [AllenInstitute/bmtk#265]
The Sonata [doc](https://github.com/AllenInstitute/sonata/blob/master/docs/SONATA_DEVELOPER_GUIDE.md#simulation-output---reports) say you can pick a dt, end time, and start time when recording reports. In reality the membrane report module does not use the specified dt, end time or start time. When using the record netconn module the run fails completely when trying to specify dt. 

Fixing this issue would allow reports to be significantly smaller in size for variables that do not need to be monitored closely like synaptic weight.

**Comment by kaeldai** [comment]
Hi @GregGlickert, I have a solution that should allow you to use the dt, start and end time within netcons and membrane reports. Are you running bmtk from a github clone of the develop branch? If so you can try a `git pull origin develop` and try it out.

For the report dt it must be a multiple of the "dt" in configuration "run" section. So must the start_time and end_time. 

Let me know if you are able to get it working, or if you are running into any issues.

**Comment by kaeldai** [comment]
CC'ing @xpliu16

**Comment by GregGlickert** [comment]
Works great! Thanks @kaeldai @xpliu16
