### ISSUE TITLE
MPI support for FilterNet

### ISSUE THREAD

**Issue by kaeldai** [AllenInstitute/bmtk#33]
Since LGN Model is none-recurrent we should be able to implement parallelization in FilterNet. The main places this should happen are at filternetwork.build_nodes() and filtersimulator.run().

**Comment by CellAssembly** [comment]
Perhaps we can discuss with Ram. I believe he implemented some form of parallelization and so might worth touching base with him.

**Comment by kaeldai** [comment]
Is implemented
