### ISSUE TITLE
Bmtk requires optional mechanisms_dir parameter

### ISSUE THREAD

**Issue by wvangeit** [AllenInstitute/bmtk#48]
According to the Sonata specification, the "mechanisms_dir" field of the circuit config is optional.
However, due to I think this line
https://github.com/AllenInstitute/bmtk/blob/develop/bmtk/simulator/bionet/config.py#L68
bmtk fails with an exception when I try to load a config that doesn't have mechanisms specification

**Comment by kaeldai** [comment]
Thanks @wvangeit - fix has already been merged.
